'use strict';
/* ============================================================
   MAPA DEL MUNDO — cada pantalla: 8 filas de 10 chars.
   Leyenda (ver 03-tiles.js): . , hierba · f flores · t hierba alta (se corta)
   p camino · s arena · n nieve · i hielo · · hojarasca · q suelo mazmorra · o madera · m barro
   W agua · ~ marisma · w vado · @ nenúfar · T Y ¥ árbol · b arbusto · Q arbusto con semilla
   r roca · M acantilado · v muro · H " D R casa · G cueva · C roca agrietada (bomba) · z zarza
   k poste (gancho) · ° agujero (vilano) · # bloque · _ placa · % pulsador · = verja · ) cerrojo
   ( llave · Ł puerta de jefe · ł llave grande · : ; antorcha · ¢ cristal · ª º Æ æ bloques
   S cartel · O runa · [ ] } altares · E Raíz · ¤ cofre · F valla · Ñ raíces del Roble · > escalera
   x felpudo · u maceta · P cama · ñ mostrador · ⌐ estante · ¶ pilar
   enemigos: B blob V murc Z escar U erizo N fantasma X rana * pincho ∞ ráfaga $ ardilla ¡ carámbano
             ¿ setón c cangrejo Φ fuego fatuo β abeja Γ golemito Σ caracol
   minijefes: ℜ Escarabajo Rey · Δ Soldado de Cera · Θ Guardián de hielo   jefes: J Topo · ! Reina · ^ Viento
   objetos: L hoja · K bomba · + gancho · £ vaina · § farol · ¬ vilano · ¦ escudo · 1-8 semillas
            9 corazón entero · ♥ cuarto de corazón · 0 diario · ( llave · ł llave grande
   vecinos: h Petra · j Lupa · y Moss · g Tilo · ö Corteza
   ============================================================ */
const MAPS={
/* ================= EL VALLE ================= */
'0,0':[ // Riscos del Silencio — semilla 1; la zarza guarda el paso al norte; cueva de Corteza
"MMMMzzMMMM",
"MG..V...⊂M",
"M..M..M..M",
"M.1M....VM",
"MM.M..r..M",
"M........M",
"M.rM.b....",
"MMM....T..",
],
'1,0':[ // Bosque de los Ecos — semilla en arbusto brillante, piedra rúnica
"TTTTTTTTTT",
"T.¿.T..T.T",
"T.T...T..T",
"T.Q.T.O..T",
"T...TT.T..",
"..T..*.b..",
"...T.T.Tø.",
"T.T....T..",
],
'2,0':[ // Claro del Primer Brote — semilla 2 y la cabaña de Corteza
"TTTRRRTTTT",
'T.."D".T.T',
"T.t.....t.",
"Tt..2.ttt.",
"..t.t.tøt.",
".B....ttt.",
"TS..t..¿.T",
"TT.....t.T",
],
'3,0':[ // Juncal del Norte — semilla en arbusto; isla con un cuarto de corazón (gancho)
"TTTTTTTTTT",
"T...WWWWWW",
"....WW♥kWW",
".t..WWWWWW",
"......WWWW",
".b.Q...WWW",
"....V...WW",
".t......WW",
],
'4,0':[ // Cascada del Ámbar — la roca agrietada esconde un cofre (bomba)
"MMMMWWMMMM",
"MMMMWWMMMM",
"WWWMW◊MMMM",
"WWWMWWM¤MM",
"WWWMWWMCMM",
"WWWWWWr0.M",
"WWW.......",
"WWWW..T..M",
],
'0,1':[ // Barrio del Roble — tu casa (izq) y la tienda de Tilo (dcha)
"M.T.....T.",
"M.RRR.RRR.",
'M."D"."D".',
"M..p...p..",
"M..ppppppp",
"M.h..S.f..",
"Mb..b..Ωt.",
"M.T.....T.",
],
'1,1':[ // Plaza de las Estaciones — el GRAN ROBLE, Raíz, los altares
"T.ÑÑÑÑÑÑ.T",
"..ÑÑÑÑÑÑ..",
"...ÑÑÑÑ...",
"..[ÑÑÑÑ]..",
"...pEp....",
"...pppp...",
"...}pp{j..",
"....pp....",
],
'2,1':[ // Pradera del Recuerdo — runa; la roca agrietada guarda un corazón entero
"..t....t..",
".rrr...t..",
".rOr..Z...",
".r9r......",
"trCr.b...W",
"..t..$..WW",
".b....t.WW",
".....t..WW",
],
'3,1':[ // Orilla de Moss — semilla 3 en la lengua de arena
"....t.....",
"..t...WWW.",
"....WWWλWW",
"..WWWWWWWW",
".sssssWW.¤",
".s3sV.WWWW",
".syss.WWWW",
"...s...WWW",
],
'4,1':[ // Orilla del Este — el poste permite cruzar a la cascada (gancho)
"..t....M..",
".......ZM.",
"WW....c..M",
"WWW.....tM",
"WWWWs....M",
"WWWWsss..M",
"WWWWss...M",
"WWWsst..MM",
],
'0,2':[ // Playa de la Hoja — la HOJA ANCESTRAL (L) y semilla en arbusto
"M.T.....T.",
"M..t..S...",
"M....s.c..",
"M.B.sss.s.",
"M..ssLsss.",
"M.ssssQss.",
"Mssssscsss",
"MMMMMMMMMM",
],
'1,2':[ // Camino de los Dientes de León — semilla 4
"T.T....T..",
".t..p..t..",
"....p..π..",
"..B.p..t..",
".t..p4....",
"..$.pp.B..",
".t.øp.....",
"MMMMMMMMMM",
],
'2,2':[ // Dunas del Este — semilla 5; grietas hacia las marismas
"..t.......",
"...$..t...",
"...sss....",
"..sssss✕s.",
".sss5ssss.",
".ssssVsss.",
"ssssscssss",
"MMMMCCMMMM",
],
'3,2':[ // Lago de las Runas — corazón entero en la isla (gancho)
"...s..WWWW",
".XOs.WWWWW",
"..ssWWWWWW",
".ssWWk9WWW",
".ssWWWWWWW",
"ssWWWWWWWW",
"ssssWWWWWW",
"MMMMMMMMMM",
],
'4,2':[ // Cabo del Vilano — un cofre tras los agujeros (vilano)
"WWWss...MM",
"WWWs.t..MM",
"WWss..°°°M",
"Wss...°.¤M",
"Wss...°°°M",
"Ws..c..MMM",
"Ws.....MMM",
"MMMMMMMMMM",
],
/* ================= LAS MONTAÑAS DEL NORTE (invierno eterno) ================= */
'0,-1':[ // Ladera de la Vigilia — carámbanos en el risco
"MMMMMMMMGM",
"M.¡n.YY..M",
"Mn..n...nM",
"M.Y...n..n",
"Mn..U....n",
"M.nn0..Y.M",
"MY...n..nM",
"MMMMnnMMMM",
],
'1,-1':[ // Campo del Deshielo — piedra rúnica; arriba, el sendero al pico
"MMMM..MMMM",
"M..i...n.M",
"M.n..i.V.M",
"n...O...iM",
"n.i...n..n",
"M...n..i.n",
"M.i...U..M",
"MMMMMMMMMM",
],
'2,-1':[ // Boca de la Cueva del Topo
"MMMMMMMMMM",
"M.MMMGMMMM",
"M.¡.nn.¡.n",
"Mn.Y..n.Yn",
"n..n...V.M",
"n.Y...nn.M",
"M.n...Y..M",
"MMMMMMMMMM",
],
'3,-1':[ // Mirador del Ámbar — un cuarto de corazón tras la grieta
"MMMMMMMMMM",
"MOn°.Y..nM",
"n°°°...MMM",
"n....n.C♥M",
"M.n....MMM",
"M..Y.n0..M",
"Mn....n.U.",
"MMMMMMMMMM",
],
'1,-2':[ // Sendero del Último Invierno — grieta, canal y el Templo de la Cima
"MMMMGMMMMM",
"Mn.n.n.✉nM",
"MWWWWWWWWM",
"MWWWWWWWWM",
"MMMMCMMMMM",
"Mn.∩∩∩.n.M",
"M..0..n..M",
"MMMM..MMMM",
],
'1,-3':[ // Cima del Viento — el Viento del Norte; cuatro braseros
"MMMMMMMMMM",
"M:r....r:M",
"M........M",
"Mr..^...rM",
"M........M",
"M..r..r..M",
"M:..nn..:M",
"MMMMnnMMMM",
],
/* ================= LAS MARISMAS DEL OTOÑO ================= */
'2,3':[ // Marisma de las Cartas — entrada
"TTTT..TTTT",
"T..t...ø.T",
".t..~~..t.",
"..m~~~~m.T",
"T.~~0~~mt.",
"..m~~~~...",
"X..t..ΨΣ.t",
"TTTTTTTTTT",
],
'1,3':[ // Tronco de la Reina — la entrada del Tronco Hueco
"TTTTTTTTTT",
"T.rrGrr.bT",
"........t.",
"..~~~..t..",
"T~~X~~m...",
"T.~~~..*..",
"T..t.m.♥..",
"TTTTTTTTTT",
],
'3,3':[ // Jardín Sumergido — un corazón entero en la isla; un cristal cruza el agua (vaina)
"TTTTTTTTTT",
"T.t...b..T",
"..b..~~..T",
".t..~~~~..",
"...~~9~~..",
"..t.~~~..T",
".X....ΣV.T",
"TTTTTTTTTT",
],
'4,-1':[ // Glaciar del Silencio — hielo y una carta del Viento (desde el mirador)
"MMMMMMMMMM",
"MiiiiiiiiM",
"Miiii¡iiiM",
"Mi✉iiiiiiM",
"MiiiiiiiiM",
"MiiiiiiiiM",
".n.iiii.nM",
"MMMMMMMMMM",
],
'0,3':[ // Cala del Silencio — una playa escondida bajo los riscos
"MMMMMMMMMM",
"MM..s..sMM",
"M.ssssssc.",
"M.sscsss..",
"Ms.✉ss..sM",
"MssWWWWssM",
"MsWWWWWWsM",
"MMMMMMMMMM",
],
'4,3':[ // Ciénaga de las Cartas — lirios y rodahojas; el viejo MOLINO (mazmorra 4), tapado por hojas podridas hasta el verano
"TTTTTTTTTT",
"T.tS.~vGvT",
".m..~~λξ.T",
"..~~~~~~.T",
"...m~~~.κT",
".Ψ...m...T",
"..t....✉.T",
"TTTTTTTTTT",
],
/* ================= LAS CUEVAS SECRETAS ================= */
'4,9':[ // Bodega del bosque — bajo el arbusto del Bosque de los Ecos
"vvvvvvvvvv",
"vqqqqqqqqv",
"vqΦqqqqΦqv",
"vqqqq✉qqqv",
"vqqqqqqqqv",
"vqqqqqqqqv",
"vqqqqxqqqv",
"vvvvvvvvvv",
],
'3,9':[ // Madriguera del camino — bajo el arbusto del Camino de los Dientes de León
"vvvvvvvvvv",
"vqqqqqqqqv",
"vqπqqqqπqv",
"vqqqq♥qqqv",
"vqqqqqqqqv",
"vqπqqqqπqv",
"vqqqqxqqqv",
"vvvvvvvvvv",
],
/* ================= LA CUEVA DEL TOPO (mazmorra 1) ================= */
'6,0':[ // Vestíbulo del Topo — al norte, la Sala de las Guardias
"vvvvqqvvvv",
"vqq;qq;qqv",
"vqvqqqqvqv",
"vqqqBqqqqq",
"vqvqqqqvqq",
"vqqqqBqqqv",
"vqqqxxqqqv",
"vvvvvvvvvv",
],
'7,0':[ // Cámara de las Raíces: empuja las rocas-raíz sobre las placas
"vvvvvvvvvv",
"vq_qq_qqqv",
"vqqqqqqqqv",
"qq#qq#qqqv",
"qqqqqqqqqv",
"vqNqq0qqqv",
"vqqq==qqqv",
"vvvvqqvvvv",
],
'8,0':[ // Sala del Escarabajo Rey
"vvvvvvvvvv",
"vqqqqqqqqv",
"vq¶qqqq¶qv",
"vqqqqℜqqqv",
"vqqqqqqqqv",
"vq¶qqqq¶qv",
"vqqqqqqqqv",
"vvvvqqvvvv",
],
'6,1':[ // Taller de las Bellotas — EMBOSCADA: al vencer, el cofre del MAPA; una grieta en el suelo (bomba) baja a la Bajada; arriba a la izquierda asoma la raíz R2 (12h)
"vvvvvvvvvv",
"vqqqqqqqqv",
"vqvqΦqvqqv",
"vqqqqq*qqq",
"vqqqqqqqqq",
"vqvqqNqvqv",
"vqqqӺqqqqv",
"vvvvvvvvvv",
],
'7,1':[ // EL FOGÓN (12h) — la sala del centro: se ve antes de las bombas y se resuelve justo después. Una bomba junto al fogón: el hielo del oeste se derrite y la raíz R1 cruza la sima hasta el pozo que baja a las Charcas
"vvvvqqvvvv",
"vqq°°qqqqv",
"vqq°°qqBqv",
"Ҳqq°°qqqqq",
"Ҳqq°°qqqqq",
"vqq°°qqҨqv",
"v°q°°qqqqv",
"vvvvvvҜvvv",
],
'8,1':[ // Galería de los Rodapúas — cerrojo al Rey (el suelo ya no baja: abajo están las Hondonadas)
"vvvv))vvvv",
"vqqqqqqqqv",
"vqUqqqqUqv",
"qqqqqqqqqv",
"qqqqqqqqqv",
"vqUqqqqUqv",
"vq♣qqqqqqv",
"vvvvvvvvvv",
],
'6,2':[ // LAS HONDONADAS · La Bajada — aquí cae quien baja por la grieta del Taller; la raíz R2 la cruza y sube; al sur, un cerrojo a las Cuestas
"vvvvvvvvvv",
"vqqqqqqqqv",
"vqqqqqqqqv",
"vqqBqqqqqq",
"vqqqqqqqqq",
"vq♣qqqqBqv",
"vqqqqqqqqv",
"vvvv)vvvvv",
],
'8,2':[ // LAS HONDONADAS · Refugio del Topo Real — cuatro fogones helados: el Topo sale donde hay calor
"vvvvvvvvvv",
"vqqqqqqqqv",
"vqҨqqqqҨqv",
"qqqqqJqqqv",
"qqqqqqqqqv",
"vqҨqqqqҨqv",
"v♣qqqqqq♣v",
"vvvvvvvvvv",
],
'6,3':[ // LAS HONDONADAS · Las Cuestas — las bellotas ruedan: la rampa lleva al cruce; con la roca en la placa, la rama del sur cruza la sima hasta el fogón F3 del otro lado (la mecha decide dónde estalla); su calor despierta R4, que tiende el puente
"vvvvqvvvvv",
"vqqqqqqqqv",
"vqqqqqqqqv",
"vᐅᐅᐅᐅᐅ⇢⇢⇢v",
"vqqqq⇣°°qҜ",
"vq#q_⇣°°qq",
"vq♣qq⇢⇢⇢Ҩv",
"vvvvvvvvvv",
],
'7,3':[ // LAS HONDONADAS · La Cripta de la Raíz — la llave grande en su isla; la raíz madre (R3) solo despierta con los fogones del Fogón y de las Charcas
"vvvvvvvvvv",
"v°°°qq°°°v",
"v°°°qł°°°v",
"v°°°°°°°°v",
"v°°°°°°°°v",
"qqqqqqqqqv",
"vqqqqqqqqv",
"vvvvvҜvvvv",
],
/* ================= LOS ANILLOS DEL ROBLE (la mazmorra final, 12i) ================= */
'22,4':[ // LOS ANILLOS DEL ROBLE · Anillo del invierno · La plaza del último invierno — se entra por el hueco del tronco; el ventisquero solo se va si el año gira (12i)
"TTTTTTTTTT",
"Tf.....Ꞙ.T",
"T......Ꞙ.T",
"T...Ꝡ..Ꞙ..",
"T......Ꞙ.T",
"Tf.....Ꞙ.T",
"T...xx.Ꞙ.T",
"TTTTTTTTTT",
],
'23,4':[ // LOS ANILLOS DEL ROBLE · Anillo del invierno · El estanque de las dos estaciones — en invierno el bloque resbala hasta el capullo helado; en verano se hunde y deja una piedra (resolvedor: 14 pasos; sin piedra, sin verano o sin invierno no hay camino, ni con el gancho)
"TTTTTTT.TT",
"T..WWWr.TT",
"T..W..r.TT",
"...Ꞥ.#WꞤTT",
"T..W..WWTT",
"T..WWWWWTT",
"T..WWWWWTT",
"TTTTTTTTTT",
],
'23,3':[ // LOS ANILLOS DEL ROBLE · Anillo del invierno · El desgarro — la Oruga del Olvido: solo le duele la cola; al final huye por el desgarro, más adentro
"TTTTꞺTTTTT",
"T........T",
"T.WWWWWW.T",
"T.WWWWWW.T",
"T.WWWWWW.T",
"T.WWWWWW.T",
"T........T",
"TTTTTTT.TT",
],
'23,2':[ // LOS ANILLOS DEL ROBLE · Anillo del otoño · La plaza de las escobas — el recuerdo: el valle barre las hojas con rabia; el barro solo se cruza helado
"TTTTTTTTTT",
"T...ꟄꟄꟄ.fT",
"T...ꟄꟄꟄ..T",
"....ꟄꟄꟄ..T",
"T...ꟄꟄꟄ..T",
"Tf..ꟄꟄꟄ..T",
"T...ꟄꟄꟄ..T",
"TTTTTTTTTT",
],
'22,2':[ // LOS ANILLOS DEL ROBLE · Anillo del otoño · El barrizal — un bloque hundido en el barro deja una piedra donde esperar el otoño (resolvedor: 14 pasos; sin el bloque o sin cualquier estación no hay camino; ni el gancho ni el salto lo rompen; sin planeo)
"T.TTTTTTTT",
"TꞗꞗꞗꟄꟄꟄ..T",
"TꞗꞗꞗꟄꟄꟄ#.T",
"TꞗꞗꞗꟄꟄꟄ...",
"TꞗꞗꞗꟄꟄꟄ..T",
"TꞗꞗꞗꟄꟄꟄ..T",
"TꞗꞗꞗꟄꟄꟄ..T",
"TTTTTTTTTT",
],
'22,1':[ // LOS ANILLOS DEL ROBLE · Anillo del otoño · El desgarro — la Oruga vuelve, más larga y más rápida
"TTTTꞺTTTTT",
"T........T",
"T.f....f.T",
"T........T",
"T..ꞗꞗꞗ...T",
"T.f....f.T",
"T........T",
"T.TTTTTTTT",
],
'25,2':[ // LOS ANILLOS DEL ROBLE · Anillo del verano · El prado de la Reina — el recuerdo: la Reina le pide descanso al Roble joven; el sol del verano entra por un claro de la copa y derrite la cera de la salida (12g, 12i)
"TTTTTTTTTT",
"Tf......fT",
"T...Ꝡ....T",
"Ѡ........Ꞵ",
"T........T",
"Tf......fT",
"T........T",
"TTTTTTTTTT",
],
'24,2':[ // LOS ANILLOS DEL ROBLE · Anillo del verano · El claro del sol — el arbusto del propio verano le tapa la luz: hay que quemarlo en otoño, cuando está seco, para que el sol del verano llegue a la cera
"TTTTTꞴTTTT",
"Tf.WW.WW.T",
"T..WWꞒWW.T",
"T..WW.ꞤꞤ..",
"T..WW.WW.T",
"Tf.WW.WW.T",
"T..WW.WW.T",
"TTTTTѠTTTT",
],
'24,3':[ // LOS ANILLOS DEL ROBLE · Anillo del verano · El desgarro — la Oruga, otra vez: más larga y más rápida; el desgarro se abre abajo
"TTTTT.TTTT",
"T........T",
"T.f....f.T",
"T..WWWW..T",
"T..WWWW..T",
"T.f....f.T",
"T........T",
"TTTTꞺTTTTT",
],
'24,1':[ // LOS ANILLOS DEL ROBLE · Anillo de la primavera · El primer día — el recuerdo: la Tierra planta dos semillas; en primavera la enredadera del semillero tiende el puente sobre la sima
"TTTT.TTTTT",
"T........T",
"T.f....f.T",
"T°°°°°°°°T",
"T°°°°°°°°T",
"T°°°°°°°°T",
"T...Ꞓ....T",
"TTTTTTTTTT",
],
'24,0':[ // LOS ANILLOS DEL ROBLE · Anillo de la primavera · El último desgarro — la Oruga, en su forma más grande; al final huye hacia la médula
"TTTTꞺTTTTT",
"T........T",
"T.Ꞓ....Ꞓ.T",
"T........T",
"T...ff...T",
"T.Ꞓ....Ꞓ.T",
"T........T",
"TTTT.TTTTT",
],
'23,-1':[ // LOS ANILLOS DEL ROBLE · La médula — la Crisálida cuelga en el centro; cuatro puntas de raíz (cada una de su estación) y cuatro braseros (para el eco de Cierzo) (12j)
"TTTTꝐTTTTT",
"T:......:T",
"T........T",
"T.♣......Ꝑ",
"Ꝑ......♣.T",
"T........T",
"T:......:T",
"TTTTTꝐTTTT",
],
/* ================= EL TRONCO HUECO (mazmorra 2) ================= */
'10,0':[ // Umbral del Tronco — el PRIMER RAYO (12g): la Hoja corta el tapón del nudo y el sol derrite la cera de la salida
"vvvvvvvvvv",
"vqqqqqqqqv",
"vqvq*qqvqv",
"ꝊqqqqqqqqѠ",
"vqvqqqqvqv",
"vqqqqqqqqv",
"vqqqxxqqqv",
"vvvvvvvvvv",
],
'11,0':[ // Galería del Enjambre: la llave y el cerrojo; al norte, la Colmena; al sur, un sello de cera que solo derrite la Columna
"vvvvqqvvvv",
"vqqqqβqqqv",
"vqvqqqqvqv",
"qqqvqqβqq)",
"vqqq(qqqq)",
"vqvqqqqvqv",
"vqqqqΣqqqv",
"vvvvѠvvvvv",
],
'12,0':[ // Nido del Soldado de Cera — dos nudos (este y suelo; arriba lo taparía la barra del jefe): se ablanda al cruzar un rayo de sol en picado
"vvvvvvvvvv",
"vqqqqqqqqv",
"vqqqqqqqqv",
"qqqqΔqqqqꝊ",
"qqqqqqqqqv",
"vqqqqqqqqv",
"vqqqqqqqqv",
"vvꝊvvvvvvv",
],
'10,1':[ // Canal de la Memoria — solo se cruza con el gancho
"vvvvvvvvvv",
"vqqqqqqqqq",
"vqqqqqqqqq",
"v~~~~~~~~v",
"v~~~~~~~~v",
"vqqqqqqqqv",
"vqq0qqqqqv",
"vvvvŁŁvvvv",
],
'11,1':[ // Sala de la Miel Cristalizada: la luz de la Columna baja por x=4; los pilares solo dejan torcerla al este abajo (filas 5-6) y al oeste arriba (1-3): la lente se empuja por la columna y la Hoja la gira; cerrojo al este
"vvvvqvvvvv",
"qqӁqqqvӁqv",
"qqӁqqqvӁΣv",
"vqӁqqqvӁqv",
"vqӁvqqvӁqv",
"vβӁvq⟋qӁq)",
"vqӁvqqqӁq)",
"vvvvvvvvvv",
],
'12,1':[ // Cámara de la Llave Grande — enjaulada en cera; el nudo, tras un foso de miel: solo el gancho arranca su tapón; al sur, el estanque
"vvvvvvvvvv",
"v~~qqqqqqv",
"v~~qqqѠqqv",
"Ꝋ~~qqѠłѠqv",
"v~~qqqѠqqv",
"qq¶q0qq¶qv",
"qqqβqqβqqv",
"vvvvqqvvvv",
],
'10,2':[ // Corazón del Panal — la Reina Avispa: cuatro nudos (12g); al final solo queda el del oeste
"vvvvqqvvvv",
"vqqqqqqqqv",
"vqqqqqqqqv",
"Ꝋqqqq!qqqv",
"vqqqqqqqqv",
"vqqqqqqqqꝊ",
"vqqqqqqqqv",
"vvꝊvvvvꝊvv",
],
/* ================= EL TEMPLO DE LA CIMA (mazmorra 3) ================= */
'15,2':[ // Atrio helado — entrada; galerías al oeste y al este. Hielo de verdad (12e): quien lo pisa resbala hasta chocar
"vvvvqqvvvv",
"vqqqqqqqqv",
"vqii¶¶iiqv",
"qqiiiiiiqq",
"qqiiiiiiqq",
"vqiiiiiiqv",
"vqqqqqqqqv",
"vvvvxxvvvv",
],
'15,1':[ // Sala de los agujeros (al norte ya no hay paso: a las campanas se llega por la Pista)
"vvvvvvvvvv",
"vqqqqqqqqv",
"vq°°°°°°qv",
"qqq°°°°qq)",
"qqq°°°°qq)",
"vq°°°°°°qv",
"vqqqΦqqqqv",
"vvvvqqvvvv",
],
'14,1':[ // Galería de bloques — sobre hielo de verdad: los bloques resbalan hasta el tope; el de hielo (Ж) lo derrite el farol. Dos placas abren la verja de la Pista (resolvedor: 14 movimientos)
"vvvv==vvvv",
"vii¶iiiqiv",
"vi#iiiiiiv",
"vЖiiiii#qq",
"viiiiiiiqq",
"v__iiiii¶v",
"vii¶iiqiiv",
"vvvvvvvvvv",
],
'16,1':[ // Cámara de la Llave Grande del templo
"vvvvqqvvvv",
"vqqqqqqqqv",
"vq¶qqqq¶qv",
"qqqqqłqqqv",
"qqqqqqqqqv",
"vq¶qΓqq¶qv",
"vqqqqqqqqv",
"vvvvvvvvvv",
],
'15,0':[ // Sala de las campanas: el rito de la nieve (12e) — mi sol mi re do, en cinco campanas de hielo; la de mi, en su foso (vaina o ráfaga)
"vvvvŁŁvvvv",
"vqᛟq==qᛟqv",
"vqqq==qqqv",
"qqq°°°qq°q",
"qqq°ᛟ°qq°q",
"vqq°°°qqqv",
"vqᛟqqqqᛟqv",
"vvvvvvvvvv",
],
'14,0':[ // La Pista: hielo de verdad (resolvedor: ↑ ← ↑ → ↑ ← ↓ →, sin atajo ni trampas); la llave, en la puerta del este
"vvvvvvvvvv",
"vii¶ii¶i♥v",
"viii¶¶iiiv",
"viiiiiiii(",
"v¶iiiiii¶q",
"viii¶¶iiiv",
"vi0iqqiiiv",
"vvvvqqvvvv",
],
'16,0':[ // El Guardián de Hielo (minijefe) — cede el Vilano; al norte, el Puente Roto
"vvvvqqvvvv",
"vqqqqqqqqv",
"vq¶qqqq¶qv",
"qqqqqΘqqqv",
"qqqqqqqqqv",
"vq¶qqqq¶qv",
"vqqqqqqqqv",
"vvvvqqvvvv",
],
'6,-1':[ // Sala de las Guardias — EMBOSCADA: al vencer cae una llave
"vvvvvvvvvv",
"vqqqqqqqqv",
"vq¶qBqq¶qv",
"vqqqqqqqqq",
"vqπqqqqπqq",
"vq¶qBqq¶qv",
"vqqqqqqqqv",
"vvvvqqvvvv",
],
'7,-1':[ // Galería Oscura — una llave en el saliente; la grieta del este (bomba) lleva al Eco
"vvvvvvvvvv",
"vqqqvvqq(v",
"vqUqvvqqqv",
"qqqqqqqqqC",
"qqqqqqqqqC",
"vqVqvvqVqv",
"v♣qqvvqqqv",
"vvvvvvvvvv",
],
'8,-1':[ // Cámara del Eco — la BRÚJULA y un cuarto de corazón
"vvvvvvvvvv",
"vqqqqqqqqv",
"vqΦqqqqΦqv",
"qqqq¤qqqqv",
"qqqqqqqq♥v",
"vqΦqqqqΦqv",
"vqqqqqqqqv",
"vvvvvvvvvv",
],
'7,2':[ // LAS HONDONADAS · Las Charcas Heladas — aquí baja la raíz R1; el fogón F2 derrite el hielo del este (la puerta del jefe y un cofre) y despierta R2
"vvvvvvvvvv",
"vqqqqqqqqv",
"vqӂqqqqҲҲv",
"qqqҨqӂqҲqŁ",
"qqqqqqqҲqŁ",
"vqӂqqӂqҲqv",
"vqqqqqqҲ¤v",
"vҜvvvvvvvv",
],
'11,-1':[ // Colmena Alta — EMBOSCADA: al vencer cae una llave; arriba, el nudo de la COLUMNA (solo el gancho llega)
"vvvvꝊvvvvv",
"vqq°°°qqqv",
"vqβvqqvβqv",
"qqqqqqqqqq",
"qqqqΣqqqqq",
"vqβvqqvΣqv",
"vqqqqqqqqv",
"vvvvqqvvvv",
],
'10,-1':[ // Paso de los Agujeros — el gancho cruza el foso hasta la BRÚJULA
"vvvvvvvvvv",
"vqqqq°°°qv",
"vq¤qq°°°qv",
"vqqqq°°°qq",
"vqqqq°°°qq",
"vqVqq°°°qv",
"vqqqq°°°qv",
"vvvvvvvvvv",
],
'12,-1':[ // Despensa de Miel — el MAPA del tronco
"vvvvvvvvvv",
"vqqqqqqqqv",
"vq¿qq¤q¿qv",
"qqqqqqqqqv",
"qqqqqqqqqv",
"vq¿qqqq¿qv",
"vqqqqqqqqv",
"vvvvvvvvvv",
],
'12,2':[ // Estanque del Panal — con el gancho: el ZURRÓN DE BELLOTAS y un cuarto
"vvvvqqvvvv",
"vqqqqqqqqv",
"v~~~~~~~~v",
"v~~~~~~~~v",
"v~~~~~~~~v",
"vqq♥qqq¤qv",
"vqqqVqqqqv",
"vvvvvvvvvv",
],
'14,2':[ // Galería del Hielo — EMBOSCADA de golemitos (solo caen con bombas): el MAPA
"vvvvvvvvvv",
"vqqqqqqqqv",
"vqΓqqqqΓqv",
"vqqqBqqqqq",
"vqqqqqqqqq",
"vq♣qqqq♣qv",
"vqqqqqqqqv",
"vvvvvvvvvv",
],
'16,2':[ // Capilla de las Llamas — dos antorchas abren la verja de la BRÚJULA
"vvvvvvvvvv",
"v:qvvvvq:v",
"vqqvq¤vqqv",
"qqqv==vqqv",
"qqqqqqqqqv",
"vqNiiiiiqv",
"vqiiiiiiqv",
"vvvvvvvvvv",
],
'16,-1':[ // Puente Roto — el aire baja y el vilano no planea... salvo en la corriente (Ш: una ráfaga la hace soplar)
"vvvvvvvvvv",
"v°°°°°Шq♥v",
"v°°°°°°°°v",
"v°°°°°°°°v",
"v°°°°°°°°v",
"v°°°°°°°°v",
"vqVqqШqqqv",
"vvvvqqvvvv",
],
/* ================= EL MOLINO DE LA HOJARASCA (mazmorra 4 · el Otoño) =================
   ξ hojarasca (el molinillo la barre; LEAF_HIDE dice qué tapa) · ψ molinete (gira con el soplo)
   κ cuervo · η caballero de hoja · ρ raíz trampa · Ξ el Espantapájaros · Λ el Ciervo de Ámbar */
'19,2':[ // Zaguán del Molino — entrada; la hojarasca guarda bayas
"vvvvqqvvvv",
"vqqqqqqκqv",
"vqξqqΨqqqv",
"qqqqqqqqqq",
"qqqqqqqqqq",
"vq¶qqqqξqv",
"vqqqqqqqqv",
"vvvvxxvvvv",
],
'18,2':[ // Granero — EMBOSCADA: al vencer cae una llave; en el rincón, un cofre tras la compuerta del SUR (la Rueda Mayor, 12f)
"vvvvvvvvvv",
"vξqqqqq=¤v",
"vq¶qκqq¶=v",
"vqqqqqqqqq",
"vqqηqqqqqq",
"vq¶qqκq¶qv",
"vqqqqqqqξv",
"vvvvvvvvvv",
],
'20,2':[ // Sala de los Sacos — el MAPA tras la pared agrietada; bellotero
"vvvvqqvvvv",
"vqqqqqqqqv",
"v♣qqqqvvvv",
"qqqqqqC¤qv",
"qqqqqqvvvv",
"vqqqqqqqqv",
"vqqκqqqρqv",
"vvvvvvvvvv",
],
'19,1':[ // Sala de los Engranajes — la RUEDA MAYOR (12f): cada ráfaga la gira un cuarto; su aspa roja abre una compuerta lejos de aquí
"vvvvqqvvvv",
"vqqqqqqqqv",
"vq¶qqqq¶qv",
")qqqЯЯqqqq",
")qqqЯЯqqqq",
"vq¶qρqq¶qv",
"vqqqqqqqqv",
"vvvvqqvvvv",
],
'18,1':[ // Pajar del Espantapájaros (minijefe) — cede el MOLINILLO
"vvvvvvvvvv",
"vqqqqqqqqv",
"vq¶qqqq¶qv",
"vqqqqΞqqqq",
"vqqqqqqqqq",
"vq¶qqqq¶qv",
"vqqqqqqqqv",
"vvvvvvvvvv",
],
'20,1':[ // El Foso de los Sacos (12f) — la ráfaga empuja sacos por el foso; uno en cada placa abre el norte (resolvedor: 6 ráfagas)
"vvvv==vvvv",
"vqqqqqqqqv",
"vqшѪшшѲшqv",
"qqѲшшшшшqv",
"qqшшшѲшЮqv",
"vqЮшшшѪшqv",
"vqqqqqqqqv",
"vvvvqqvvvv",
],
'20,0':[ // Sala del Viento — su compuerta se abre con la rueda al ESTE; el molinete del norte mueve el eje de la Cámara de la Llave
"vvvvqqvvvv",
"vqqqqqqqqv",
"vqqqκqqψqv",
"vvvv==vvvv",
"vqqqqqqqqv",
"vqqqqqqηqv",
"vqqqqqqqqv",
"vvvvqqvvvv",
],
'20,-1':[ // Cámara de la Llave — tres molinetes en fila (y hojarasca en medio): abren la verja solo si el eje aún gira
"vvvvvvvvvv",
"vqqqqqqqκv",
"vqψξψqψqqv",
"vqqqqqqqqv",
"vqqqqqvvvv",
"vqηqqq=łvv",
"vqqqqqvvvv",
"vvvvqqvvvv",
],
'19,0':[ // Sala de las Aspas — compuertas de la rueda: NORTE (la puerta del guardián) y OESTE (el Laberinto); un cuarto de corazón bajo las hojas
"vvvvŁŁvvvv",
"vqqq==qqqv",
"vqξqqqqξqv",
"=qqqqqqqqv",
"=qqqηqqqqv",
"vqξqqqqξqv",
"vqqqκqqqqv",
"vvvvqqvvvv",
],
'18,0':[ // Laberinto de Hojarasca — bajo las hojas, suelo o agujero: la BRÚJULA
"vvvvvvvvvv",
"v¤qξξξqqqv",
"vqqξξξqqqv",
"vqqξξξqqqq",
"vqqξξξqqqq",
"vqqξξξqκqv",
"vqqξξξqqqv",
"vvvvvvvvvv",
],
'19,-1':[ // Lecho del Ciervo — EL CIERVO DE ÁMBAR
"vvvvvvvvvv",
"vqqqqqqqqv",
"vqqqqqqqqv",
"vqqqqΛqqqv",
"vqqqqqqqqv",
"vqqqqqqqqv",
"vqqqqqqqqv",
"vvvvqqvvvv",
],
/* ================= LA GRUTA DE LOS ECOS (cueva oscura del risco) ================= */
'5,9':[
"vvvvvvvvvv",
"vqqqqqqqqv",
"vqvqΦqvqqv",
"vqqqq¤qqqv",
"vqvqqqqvqv",
"vqqΦqqqqqv",
"vqqqxxqqqv",
"vvvvvvvvvv",
],
/* ================= EL ECO DE LOS GUARDIANES (post-juego, bajo la Gruta) ================= */
'0,12':[ // Antesala del Eco — una runa cuenta de qué va esto
"vvvvvvvvvv",
"vq¶qqqq¶qv",
"vqqqqqqqqv",
"vqqqOqqqqq",
"vqqqqqqqqq",
"vq¶qqqq¶qv",
"vqqqqxqqqv",
"vvvvvvvvvv",
],
'1,12':[ // Eco del Topo Real
"vvvvvvvvvv",
"vqqqqqqqqv",
"v♣qqqqqq♣v",
"qqqqqqqqq=",
"qqqqqqqqq=",
"v♣qqqqqq♣v",
"vqqqqqqqqv",
"vvvvvvvvvv",
],
'2,12':[ // Eco de la Reina Avispa
"vvvvvvvvvv",
"vqqqqqqqqv",
"vqqqqqqqqv",
"qqqqqqqqq=",
"qqqqqqqqq=",
"vqqqqqqqqv",
"vqqqqqqqqv",
"vvvvvvvvvv",
],
'3,12':[ // Eco del Ciervo de Ámbar
"vvvvvvvvvv",
"vqqqqqqqqv",
"vq¶qqqq¶qv",
"qqqqqqqqq=",
"qqqqqqqqq=",
"vq¶qqqq¶qv",
"vqqqqqqqqv",
"vvvvvvvvvv",
],
'4,12':[ // Eco del Viento del Norte — cuatro braseros
"vvvvvvvvvv",
"v:qqqqqq:v",
"vqqqqqqqqv",
"qqqqqqqqq=",
"qqqqqqqqq=",
"vqqqqqqqqv",
"v:qqqqqq:v",
"vvvvvvvvvv",
],
/* ================= LOS ESCONDITES DEL VALLE (12c-secrets) ================= */
'0,10':[ // Cueva del Eco Dormido — tras la grieta de los Riscos (bomba); el cuarto, tras otra grieta
"vvvvvvvvvv",
"vqqqv♥vqqv",
"vqOqvCvqqv",
"vqqqqqqqΦv",
"vq¶qqqq¶qv",
"vqΦqqqqqqv",
"vqqqqxqqqv",
"vvvvvvvvvv",
],
'1,10':[ // Manantial de Savia — bajo el corro de las hadas del Claro; el agua cura y en la isla late un corazón (gancho)
"vvvvvvvvvv",
"vqqwwwwqSv",
"vqwwWWwwqv",
"vqwWW9Wwqv",
"vqwwWWwwqv",
"vqqwwqwwqv",
"vqqqqxqqqv",
"vvvvvvvvvv",
],
'2,10':[ // Madriguera Helada — la boca helada de la Ladera; tres braseros abren la verja (farol)
"vvvvvvvvvv",
"v:qvqqqvqv",
"vqqvq¤qvqv",
"vqqvv=vvqv",
"vqΦqqqqq:v",
"vqqqqqqΦqv",
"v:qqqxqqqv",
"vvvvvvvvvv",
],
'3,10':[ // Refugio de la Ciénaga — bajo el arbusto de la Marisma; ranas, un cofre y una runa
"vvvvvvvvvv",
"vq~~qqq~Ov",
"vq~mq¤qmqv",
"vqmqXqqqqv",
"v~~qqqX~~v",
"vqqqqqqqqv",
"vq¶qqxq¶qv",
"vvvvvvvvvv",
],
'5,12':[ // El Alba — la recompensa del eco
"vvvvvvvvvv",
"vq¶qqqq¶qv",
"vqqqq9qqqv",
"qqqq¤qqqqv",
"qqqqqqqqqv",
"vq¶qqqq¶qv",
"vqqqqqqqqv",
"vvvvvvvvvv",
],
/* ================= INTERIORES ================= */
'9,9':[ // la casa de Sprout
"IIIIIIIIII",
"IuoooⒷoouI",
"IooPoooooI",
"IoooooouoI",
"IuoooooooI",
"IooooooooI",
"Iooooooo0I",
"IIIIIxIIII",
],
'8,9':[ // la tienda de Tilo
"IIIIIIIIII",
"Iu⌐oⒷ⌐oouI",
"IooogooooI",
"IoñññññooI",
"IooooooooI",
"IuoooooouI",
"IooooooooI",
"IIIIIxIIII",
],
'7,9':[ // la cabaña de Corteza (amuletos)
"IIIIIIIIII",
"IⒷu⌐oo⌐uⒷI",
"IooooöoooI",
"IooñññññoI",
"IooooooooI",
"IuoooooouI",
"IooooooooI",
"IIIIIxIIII",
],
};
/* cofres: 'sx,sy:x,y' → contenido */
const CHESTS={
  '4,0:7,3':{kind:'amulet',id:'buho'},
  '4,2:8,3':{kind:'amulet',id:'viento'},
  '5,9:5,3':{kind:'amulet',id:'raiz'},
  '7,2:8,6':{kind:'amulet',id:'erizo'}, // tras el hielo de las Charcas (12h)
};
/* nombres de lugar */
const PLACE_NAMES={'0,0':'Riscos del Silencio','1,0':'Bosque de los Ecos','2,0':'Claro del Primer Brote','3,0':'Juncal del Norte','4,0':'Cascada del Ámbar','0,1':'Barrio del Roble','1,1':'Plaza de las Estaciones','2,1':'Pradera del Recuerdo','3,1':'Orilla de Moss','4,1':'Orilla del Este','0,2':'Playa de la Hoja','1,2':'Camino de los Dientes de León','2,2':'Dunas del Este','3,2':'Lago de las Runas','4,2':'Cabo del Vilano','0,-1':'Ladera de la Vigilia','1,-1':'Campo del Deshielo','2,-1':'Boca de la Cueva','3,-1':'Mirador del Ámbar','1,-2':'Sendero del Último Invierno','1,-3':'Cima del Viento','2,3':'Marisma de las Cartas','1,3':'Tronco de la Reina','3,3':'Jardín Sumergido',
'22,4':'La plaza del último invierno','24,1':'El primer día','23,-1':'La médula','24,0':'El último desgarro','25,2':'El prado de la Reina','24,2':'El claro del sol','24,3':'El desgarro del verano','23,2':'La plaza de las escobas','22,2':'El barrizal','22,1':'El desgarro del otoño','23,4':'El estanque de las dos estaciones','23,3':'El desgarro del invierno','6,0':'Vestíbulo del Topo','7,0':'Cámara de las Raíces','8,0':'Trono del Escarabajo','6,1':'Taller de las Bellotas','7,1':'El Fogón','8,1':'Galería de los Rodapúas','6,2':'La Bajada','7,2':'Las Charcas Heladas','8,2':'Refugio del Topo Real','6,3':'Las Cuestas','7,3':'La Cripta de la Raíz','6,-1':'Sala de las Guardias','7,-1':'Galería Oscura','8,-1':'Cámara del Eco','11,-1':'Colmena Alta','10,-1':'Paso de los Agujeros','12,-1':'Despensa de Miel','12,2':'Estanque del Panal','14,2':'Galería del Hielo','16,2':'Capilla de las Llamas','16,-1':'Puente Roto',
'10,0':'Umbral del Tronco','11,0':'Galería del Enjambre','12,0':'Nido del Soldado','10,1':'Canal de la Memoria','11,1':'Sala de la Miel','12,1':'Cámara de la Llave','10,2':'Corazón del Panal',
'15,2':'Atrio Helado','15,1':'Sala del Vacío','14,1':'Galería de Bloques','16,1':'Cámara de la Llave','15,0':'Sala de las Campanas','14,0':'Pista de Hielo','16,0':'Trono del Guardián',
'5,9':'Gruta de los Ecos','0,12':'Antesala del Eco','1,12':'Eco del Topo','2,12':'Eco de la Reina','3,12':'Eco del Ciervo','4,12':'Eco del Viento','5,12':'El Alba','4,9':'Bodega del Bosque','3,9':'Madriguera del Camino','4,-1':'Glaciar del Silencio','0,3':'Cala del Silencio','4,3':'Ciénaga de las Cartas','9,9':'Tu maceta','8,9':'La tienda de Tilo','7,9':'La cabaña de Corteza'};
