'use strict';
/* ---------- MAPA DEL MUNDO (4×3 pantallas de 10×8) ---------- */
const MAPS = {
'0,0':[ // NO: riscos con murciélagos — semilla 1; la zarza guarda el paso al norte
"rrrrzzrrrr",
"r..r...rrr",
"r.1..r...r",
"rr...V...r",
"r..r..r..,",
"r......V..",
"r.rr.....t",
"rrr....t..",
],
'1,0':[ // bosque laberinto — semilla en arbusto (Q)
"TTTTTTTTTT",
"T...T....T",
"..T...T.T.",
"T.Q.T...T.",
"T...TT.T..",
".TT....O.T",
"T...T.TT..",
".T...T....",
],
'2,0':[ // claro del bosque — semilla 2
"TTTTTTTTTT",
"T....T...T",
"..t.t...t.",
".t..2..B..",
"....t.....",
".B....t...",
"T...t....t",
"TT....t..T",
],
'3,0':[ // lago norte — semilla en arbusto (Q)
"TTTTTTTTTT",
"T...WWWWWT",
"....WWWWWr",
".t..WWWWWr",
"......WWWr",
".b.Q...WWr",
"....V...Wr",
".t......Wr",
],
'0,1':[ // EL BARRIO DEL ROBLE — tu casa (O) y la tienda de Tilo (E); el pueblo de verdad
"r...T..T..",
"r.RRR.RRR.",
"r.HDH.HDH.",
"r..p...p..",
"r..ppppppp",
"r.h..S.f..",
"r...b..t..",
"r....f....",
],
'1,1':[ // LA PLAZA SAGRADA — el GRAN ROBLE en el centro, Raíz a sus raíces,
        // altares de primavera [ y verano ] a sus flancos; el del invierno, apartado al sur
"T.ÑÑÑÑÑÑ.T",
"..ÑÑÑÑÑÑ..",
"...ÑÑÑÑ...",
"..[ÑÑÑÑ]..",
"...pEp....",
"...pppp...",
"...}pp.j..",
"....pp....",
],
'2,1':[ // pradera este — una runa duerme tras la roca agrietada (bomba)
        // OJO: el borde este (col 9, filas 0-3) es el ÚNICO paso seco al lago: no tapiarlo
"..t....t..",
".rrr...t..",
".rOr..Z...",
".rCr......",
"t....B...W",
"..t..$..WW",
".b....t.WW",
".....t..WW",
],
'3,1':[ // lago — semilla 3 en la lengua de arena
".....WWWWr",
"..t..WWWWr",
"....WWWWWr",
"..WWWWWWWr",
".sssssWWWr",
".s3sV.WWWr",
".syss.WWWr",
"...s...WWr",
],
'0,2':[ // playa suroeste — la HOJA ANCESTRAL (L) y semilla en arbusto (Q)
"r.........",
"r..t..S...",
"r....s.V..",
"r.B.sss.s.",
"r..ssLsss.",
"r.ssssQss.",
"rsssssssss",
"rrrrrrrrrr",
],
'1,2':[ // pradera sur — semilla 4
"....p.....",
".t..p..t..",
"....p.....",
"..B.p..t..",
".t..p4....",
"..$.pp.B..",
".t...p....",
"rrrrrrrrrr",
],
'2,2':[ // playa este — semilla 5; grietas hacia las marismas
"..t.......",
"...$..t...",
"...sss....",
"..ssssss..",
".sss5ssss.",
".ssssVsss.",
"ssssssssss",
"rrrrCCrrrr",
],
'3,2':[ // rincón del lago
"...s..WWWr",
"..Os.WWWWr",
"..ssWWWWWr",
".ssWW9WWWr",
".ssWWWWWWr",
"ssWWWWWWWr",
"ssssWWWWWr",
"rrrrrrrrrr",
],
/* ====== LAS MONTAÑAS DEL NORTE (invierno eterno) ====== */
'0,-1':[ // ladera nevada — ojo con los carámbanos del risco
"MMMMMMMMMM",
"M.¡n.YY..M",
"Mn..n...nM",
"M.Y...n..n",
"Mn..U....n",
"M.nn0..Y.M",
"MY...n..nM",
"MMMMnnMMMM",
],
'1,-1':[ // campo helado — piedra rúnica; arriba, el sendero al pico
"MMMM..MMMM",
"M..i...n.M",
"M.n..i...M",
"n...O...iM",
"n.i...n..n",
"M...n..i.n",
"M.i...U..M",
"MMMMMMMMMM",
],
'2,-1':[ // la boca de la cueva
"MMMMMMMMMM",
"M.MMMGMMMM",
"M.¡.nn.¡.n",
"Mn.Y..n.Yn",
"n..n...V.M",
"n.Y...nn.M",
"M.n...Y..M",
"MMMMMMMMMM",
],
'3,-1':[ // mirador — secreto tras la grieta
"MMMMMMMMMM",
"M.n..Y..nM",
"n..n...MMM",
"n....n.C9M",
"M.n....MMM",
"M..Y.n...M",
"Mn....n.VM",
"MMMMMMMMMM",
],
/* ====== LA CIMA DEL VIENTO (capítulo 3, siempre nevada) ====== */
'1,-2':[ // sendero al pico: grieta (bomba) → canal (gancho) → cumbre
"MMMM..MMMM",
"Mn....@n.M",
"M..~~~~..M",
"M..~~~~..M",
"MMMMCMMMMM",
"Mn.....n.M",
"M..0..n..M",
"MMMM..MMMM",
],
'1,-3':[ // LA CUMBRE — el Viento del Norte
"MMMMMMMMMM",
"M.r....r.M",
"M........M",
"Mr..^...rM",
"M........M",
"M..r..r..M",
"Mn..nn..nM",
"MMMM..MMMM",
],
/* ====== LA CUEVA DEL TOPO (mazmorra) ====== */
'6,0':[ // entrada con antorchas
"vvvvvvvvvv",
"vqqqqqqqqv",
"vqvqqqqvqv",
"vqqqqqqqqq",
"vqvqqqqvqq",
"vqqqqqqqqv",
"vqqqxxqqqv",
"vvvvvvvvvv",
],
'7,0':[ // sala de guardia: empuja las rocas-raíz sobre las placas
"vvvvvvvvvv",
"vq_qq_qqqv",
"vqqqqqqqqv",
"qq#qq#qqqv",
"qqqqqqqqqv",
"vqNqq0qqqv",
"vqqq==qqqv",
"vvvvqqvvvv",
],
'7,1':[ // sala del pulsador
"vvvvqqvvvv",
"vqqqqqqqqv",
"vqvqqqqvqv",
"q=qqqqqqqv",
"q=qqq%qqqv",
"vqvqqqqvqv",
"vqqqqqqqqv",
"vvvvvvvvvv",
],
'6,1':[ // sala de la Bellota
"vvvvvvvvvv",
"vqqqqqqqqv",
"vqvqKqvqqv",
"vqqqqq*qqq",
"vqqqqqqqqq",
"vqvqqNqvqv",
"vqqqqqqqqv",
"vvvvCCvvvv",
],
'6,2':[ // guarida del TOPO REAL
"vvvvqqvvvv",
"vqqqqqqqqv",
"vqqqqqqqqv",
"vqqqqJqqqv",
"vqqqqqqqqv",
"vqqqqqqqqv",
"vqqqqqqqqv",
"vvvvvvvvvv",
],
'9,9':[ // interior de la casa de Sprout
"IIIIIIIIII",
"IuoooooouI",
"IooPoooooI",
"IoooooouoI",
"IuoooooooI",
"IooooooooI",
"Iooooooo0I",
"IIIIIxIIII",
],
'8,9':[ // LA TIENDA DE TILO (casa NE del pueblo)
"IIIIIIIIII",
"Iu⌐oo⌐oouI",
"IooogooooI",
"IoñññññooI",
"IooooooooI",
"IuoooooouI",
"IooooooooI",
"IIIIIxIIII",
],
/* ====== LAS MARISMAS DEL OTOÑO ====== */
'2,3':[ // entrada de las marismas
"TTTT..TTTT",
"T..t...b.T",
".t..~~..t.",
"..~~~~~..T",
"T.~~0~~.t.",
"..~~~~~...",
"X..t...B.t",
"TTTTTTTTTT",
],
'1,3':[ // marisma oeste — el tronco hueco (mazmorra 2)
"TTTTTTTTTT",
"T.rrGrr.bT",
"T.......t.",
"T.~~~..t..",
"T~~X~~....",
"T.~~~..*..",
"T..t......",
"TTTTTTTTTT",
],
'3,3':[ // marisma este — isla con corazón
"TTTTTTTTTT",
"T.t...b..T",
"..b..~~..T",
".t..~~~~.T",
"...~~9~~.T",
"..t.~~~..T",
".X.....V.T",
"TTTTTTTTTT",
],
/* ====== EL TRONCO HUECO (mazmorra 2) ====== */
'10,0':[ // entrada
"vvvvvvvvvv",
"vqqqqqqqqv",
"vqvqqqqvqv",
"vqqqqqqqqq",
"vqvqqqqvqq",
"vqqqqqqqqv",
"vqqqxxqqqv",
"vvvvvvvvvv",
],
'11,0':[ // enjambre: coge la llave-bellota y abre el cerrojo
"vvvvvvvvvv",
"vqqqqVqqqv",
"vqvqqqqvqv",
"qqqvqqVqqv",
"qqqq(qqqqv",
"vqvqqqqvqv",
"vqqqqBqqqv",
"vvvv))vvvv",
],
'11,1':[ // sala de la RAÍZ-GANCHO
"vvvvqqvvvv",
"vqqqqqqqqv",
"vqvq+qvqqv",
"vqqqqqqqqv",
"vqvqqqvqqv",
"qqqqqqqqqv",
"qqvqqqqqqv",
"vvvvvvvvvv",
],
'10,1':[ // el canal — solo se cruza con el gancho
"vvvvvvvvvv",
"vqqq>qqqqv",
"vqqqqqqqqv",
"v~~~~~~~~v",
"v~~~~~~~~v",
"vqqqqqqqqq",
"vqqqq0qqqq",
"vvvvvvvvvv",
],
'10,2':[ // panal de la REINA AVISPA
"vvvvvvvvvv",
"vqqqqqqqqv",
"vqqqqqqqqv",
"vqqqq!qqqv",
"vqqqqqqqqv",
"vqqqqqqqqv",
"vqqqxxqqqv",
"vvvvvvvvvv",
],
};

